### ISSUE TITLE
Support for Big Sur?

### ISSUE THREAD

**Issue by 3raxton** [Frostbitee08/NotificationShortcuts#2]
Hey there, I love this app and appreciate the work you've put into it. It's a crucial part of my daily workflow. Do you have any plans to add support for Big Sur, or would it be wise to look for another app?

Again, great work on NotifcationShortcuts; I can't live without it!

**Comment by mimkorn** [comment]
I tried to install it as well, but on the setup screen after doing the four steps, it loads forever with Waiting... :(

**Comment by m-titov** [comment]
same for me

**Comment by bucketfish** [comment]
yea, me too :/
when i tried building from source i get an error - i'll update if it works! 😔
